In [2]:
print("Hello Numpy")

Hello Numpy


In [1]:
import numpy as np
import sys

In [6]:
# creating an array
array1 = np.array([1,2,3,4,5]) # one dimensional array
print(array1)

[1 2 3 4 5]


In [5]:
# we can initialize 2d array of floats
array2 = np.array([[1.0,2,3.0],[4,5,6.0]]) # two dimensional array like matrix
print(array2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# get dimensions of an array
# ndim - number of dimensions
print(array1.ndim)
print(array2.ndim)

1
2


In [8]:
# get shape of the array
# returns tuple of len = (number of dimensions)
# each value in the tuple is size of each dimension in order 
print(array1.shape) 
print(array2.shape)

(5,)
(2, 3)


In [11]:
# get the type of the array
# numpy arrays can contain only one datatype in the array
# for eg., it must contain all int or all floats, no mix of float and ints like lists
print(array1.dtype)
print(array2.dtype)

int32
float64


In [12]:
# get the data size of any of the item inside the numpy array
print(array1.itemsize) # returns number of bytes of an element in the array
print(array2.itemsize) # returns number of bytes of an element in the array

4
8


In [13]:
# get the total size of the array
# it returns total number of elements in the whole array
print(array1.size) # 5
print(array2.size) # 2*3

5
6


In [15]:
# get total memory size of the array
print(array1.itemsize * array1.size)
print(array1.nbytes) # sends us the total number of bytes required to store the whole array
print(array2.itemsize * array2.size)
print(array2.nbytes) # sends us the total number of bytes required to store the whole array

20
20
48
48


In [18]:
# initialize datatype along with the array
array3 = np.array([1,2,3,4,5], dtype = "float64")
print(array3, array3.dtype)

[1. 2. 3. 4. 5.] float64


In [19]:
# summary
array4 = np.array([[1,2,3,4,5], [2,3,4,5,6]], dtype = "float64")
print("array = ", array4)
print("Number of Dimensions = ", array4.ndim)
print("Shape of the array = ", array4.shape)
print("DataType of the element of the array = ", array4.dtype)
print("size of the array (Total no. of elements) = ", array4.size)
print("Bytes of the element of the array = ", array4.itemsize)
print("Total memory size of the array in bytes = ", array4.nbytes)

array =  [[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]]
Number of Dimensions =  2
Shape of the array =  (2, 5)
DataType of the element of the array =  float64
size of the array (Total no. of elements) =  10
Bytes of the element of the array =  8
Total memory size of the array in bytes =  80


In [37]:
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# get specific element of the array
# 2d array = [row, col]
# tensors = [ind1, ind2, ind3,... ]
print(array5[1,0])
print(array5[-1,0]) # we can also use negative indices like lists
print(array5[-1,-1])
# print(array5[-1][-1]) - don't use this syntax, it has ambiguity

8
8
14
14


In [31]:
# get a specific row of the array
# this method can also be done in lists
print(array5[0])
# ":" will iterate through all the elements in that dimension 
print(array5[0, :])
# print(array5[0][:]) - don't use this syntax, it has ambiguity

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [32]:
# get a specific column of the array
# this method cannot also be done in lists
# : says iterate through all the rows and give us 
print(array5[:, 1])
# print(array5[:][1]) - don't use this syntax, it has ambiguity

[2 9]


In [35]:
# Slice numpy arrays
# syntax - array[startind1:endind1:stepsize1, startind2:endind2:stepsize2, startind3:endind3:stepsize3,... ]

# we will get 9 to 13 elements
print(array5[1, 1:-1])

# we will get 9 to 13 elements, by skipping one element
print(array5[1, 1:-1:2])

[ 9 10 11 12 13]
[ 9 11 13]


In [46]:
# edit elements in the numpy array

# change a single element
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "before")
array5[1,5] = 20
print(array5, "after")
print("--------------------------------------------")

# change all elements in a column to the same value
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "before")
array5[:, 2] = 20
print(array5, "after")
print("--------------------------------------------")

# change all elements in a column to different values
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "before")
array5[:, 2] = [99,100] # we can either pass in list or numpy array but they must be of same dimensions
print(array5, "after")
print("--------------------------------------------")

# change all elements in a row to different values
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "before")
array5[0, :] = np.array([99, 100, 101, 102, 103, 104, 105]) # we can either pass in list or numpy array
print(array5, "after")
print("--------------------------------------------")

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] before
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]] after
--------------------------------------------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] before
[[ 1  2 20  4  5  6  7]
 [ 8  9 20 11 12 13 14]] after
--------------------------------------------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] before
[[  1   2  99   4   5   6   7]
 [  8   9 100  11  12  13  14]] after
--------------------------------------------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] before
[[ 99 100 101 102 103 104 105]
 [  8   9  10  11  12  13  14]] after
--------------------------------------------


In [47]:
# Initialize different types of arrays

In [52]:
# Initialize array full of 0's
print(np.zeros((1,2,3))) # we need to specify shape of the array in brackets as argument - float64 is returned as default
print(np.zeros((1,2,3), dtype="int32")) # we need to specify shape of the array in brackets as argument

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[0 0 0]
  [0 0 0]]]


In [54]:
# Initialize array full of 1's
print(np.ones((2,3))) # we need to specify shape of the array in brackets as argument - float64 is returned as default
print(np.ones((2,3), dtype="int32")) # we need to specify shape of the array in brackets as argument

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [57]:
# other than 1's and 0's what if we wanna create an array full of different same value
print(np.full((2,3), 9)) # we need to specify shape in brackets and the value
print(np.full((2,3), 9, dtype="int32")) # we need to specify shape in brackets and the values in the array

[[9 9 9]
 [9 9 9]]
[[9 9 9]
 [9 9 9]]


In [ ]:
# create array with random values, numpy random

In [60]:
# array of random float numbers
# all the numbers are inbetween 0 and 1
print(np.random.rand(4,2)) # pass in the shape directly rather than specifying them in brackets or tuples
print(np.random.rand(*array5.shape)) # *(2,7) -> 2,7

[[0.0987358  0.15076905]
 [0.65262975 0.03514364]
 [0.26276471 0.4489846 ]
 [0.50061028 0.15056049]]
[[0.08314779 0.98196126 0.02380028 0.31592825 0.5462879  0.99828467
  0.93057831]
 [0.90874365 0.92666272 0.01839651 0.16089518 0.7789033  0.3106976
  0.86698865]]


In [63]:
# array of random integers
# low (inclusive) to high (exclusive)
# np.random.randint(low, high=None, size=None, dtype=int)
print(np.random.randint(0, 10, (4,3)))
print(np.random.randint(10, size=(4,3))) # the above line and this line is the same
# if we didn't specify low, then default value for low is 0 and size name must be specified

[[1 9 4]
 [7 3 6]
 [7 1 2]
 [8 7 0]]
[[4 2 7]
 [6 0 7]
 [9 5 6]
 [6 3 9]]


In [64]:
# create identity matrix of size n x n
# we need to pass n as argument
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# copying is same as lists
# you need to copy the function to a new variable rather than directly assigning it to it

# wrong thing to do
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "array5")
array6 = array5
array6[0,0] = 100
print(array5, "array5")

# Right thing to do
array5 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(array5, "array5")
array6 = array5.copy() # this is how we copy and assign an numpy array
array6[0,0] = 100
print(array5, "array5")

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] array5
[[100   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]] array5
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] array5
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] array5


In [6]:
# Mathematics
# https://numpy.org/doc/stable/reference/routines.math.html

In [7]:
# Element wise math operations
array7 = np.array([1,2,3,4,5,6])

# addition
print(array7 + 6)

# subtraction
print(array7 - 6)

# multiplication
print(array7 * 0)

# division
print(array7 // 3)

# power
print(array7**2)

[ 7  8  9 10 11 12]
[-5 -4 -3 -2 -1  0]
[0 0 0 0 0 0]
[0 0 1 1 1 2]
[ 1  4  9 16 25 36]


In [10]:
# add two arrays elementwise
array7 = np.array([1,2,3,4,5,6])
array8 = np.array([1,1,1,1,1,1], dtype="float64")
print(array7+array8)

[2. 3. 4. 5. 6. 7.]


In [17]:
# element wise trigonometry
# numpy trigonometry functions take radians as input

# sin, cos, tan
print(np.sin(array7))
print(np.cos(array7))
print(np.tan(array7))
print("------------------------------------------")
# sin inverse, cos inverse, tan inverse
# output is in radians
print(np.arcsin(array8))
print(np.arccos(array8))
print(np.arctan(array8))
print("------------------------------------------")
# convert radians to degrees
print(np.degrees(array7))
print("------------------------------------------")
# convert degrees to radians
print(np.radians(array7))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
------------------------------------------
[1.57079633 1.57079633 1.57079633 1.57079633 1.57079633 1.57079633]
[0. 0. 0. 0. 0. 0.]
[0.78539816 0.78539816 0.78539816 0.78539816 0.78539816 0.78539816]
------------------------------------------
[ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757
 343.77467708]
------------------------------------------
[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646 0.10471976]


In [18]:
# Statistics

In [8]:
array9 = np.array([[1,2,3],[4,5,6]])

In [9]:
# np.min is same as np.amin

# Minimum element over all the elements in the array
print(np.min(array9), "Minimum element over all the elements in the array")

# Minimum element in every column
print(np.min(array9, axis=0), "Minimum element in every column")

# Minimum element in every row
print(np.min(array9, axis=1), "Minimum element in every row")

1 Minimum element over all the elements in the array
[1 2 3] Minimum element in every column
[1 4] Minimum element in every row


In [10]:
# np.max is same as np.amax

# Maximum element over all the elements in the array
print(np.max(array9), "Maximum element over all the elements in the array")

# Maximum element in every column
print(np.max(array9, axis=0), "Maximum element in every column")

# Maximum element in every row
print(np.max(array9, axis=1), "Maximum element in every row")

6 Maximum element over all the elements in the array
[4 5 6] Maximum element in every column
[3 6] Maximum element in every row


In [11]:
# Return minimum or maximum of an array or minimum along an axis, ignoring any np.nan's
array10 = np.array([[1,2],[3,4],[np.nan ,7],[6,np.nan],[8,9]])

# Minimum element over all the elements excluding np.nan's in the array
print(np.nanmin(array10), "Minimum element over all the elements excluding np.nan's in the array")

# Minimum element in every column excluding np.nan's
print(np.nanmin(array10, axis=0), "Minimum element in every column excluding np.nan's")

# Maximum element over all the elements excluding np.nan's in the array
print(np.nanmax(array10), "Maximum element over all the elements excluding np.nan's in the array")

# Maximum element in every row excluding np.nan's
print(np.nanmax(array10, axis=1), "Maximum element in every row excluding np.nan's")


1.0 Minimum element over all the elements excluding np.nan's in the array
[1. 2.] Minimum element in every column excluding np.nan's
9.0 Maximum element over all the elements excluding np.nan's in the array
[2. 4. 7. 6. 9.] Maximum element in every row excluding np.nan's


In [26]:
# mean, median, standard deviation and variance
array9 = np.array([[1,2,3],
                   [4,5,6]])
print("shape = ", array9.shape)
print("-----------------------------------------")

# mean
print(np.mean(array9)) # mean of all the elements in the array
print(np.mean(array9, axis=0)) # mean in each column
print(np.mean(array9, axis=1)) # mean in each row
print("-----------------------------------------")

# find mean with weights
print(np.average(array9, weights=np.arange(6,0,-1).reshape(array9.shape))) # average of all the elements in the array
print(np.average(array9, axis=0, weights=np.arange(2,0,-1))) # average in each column
print(np.average(array9, axis=1, weights=np.arange(3,0,-1))) # average in each row
print("-----------------------------------------")

# median
print(np.median(array9)) # median of all the elements in the array
print(np.median(array9, axis=0)) # median in each column
print(np.median(array9, axis=1)) # median in each row
print("-----------------------------------------")

# standard deviation
print(np.std(array9)) # std of all the elements in the array
print(np.std(array9, axis=0)) # std in each column
print(np.std(array9, axis=1)) # std in each row
print("-----------------------------------------")

# variance
print(np.var(array9)) # var of all the elements in the array
print(np.var(array9, axis=0)) # var in each column
print(np.var(array9, axis=1)) # var in each row
print("-----------------------------------------")

# if the numpy array got np.nan inbetween them then we can use these functions
# np.nanmean
# np.nanmedian
# np.nanstd
# np.nanvar

shape =  (2, 3)
-----------------------------------------
3.5
[2.5 3.5 4.5]
[2. 5.]
-----------------------------------------
2.6666666666666665
[2. 3. 4.]
[1.66666667 4.66666667]
-----------------------------------------
3.5
[2.5 3.5 4.5]
[2. 5.]
-----------------------------------------
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]
-----------------------------------------
2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]
-----------------------------------------


In [27]:
# Reordering and Reorganizing arrays

In [28]:
array11 = np.array([[1,2,3,4,5,6],
                    [7,8,9,10,11,12],
                    [13,14,15,16,17,18],
                    [19,20,21,22,23,24]])
print(array11.shape)

(4, 6)


In [32]:
# reshape
# change the shape of the array
print(array11, "before")
print(array11.reshape((8,3)), "after") # send in required shape within brackets as tuples
# if we are lazy to calculate one of the shape, we can use -1, numpy will automaticall find the required shape
print(array11.reshape((8,-1)), "again after")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] before
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]] after
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]] again after


In [40]:
# vertically stacking arrays
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,0])

print(np.vstack((vector1, vector2, vector1, vector2))) # arguments must be specified in brackets or tuples  
print("------------------------------------------------")
print(np.array([vector1, vector2, vector1, vector2])) #this line is same as the above line

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]]
------------------------------------------------
[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]
 [6 7 8 9 0]]


In [45]:
# horizontally stack arrays

# example 1
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,0])
print(np.hstack((vector1, vector2))) # arguments must be specified in brackets or tuples  
print("------------------------------------------------")

# example 2
# for matrix(nxm) horizontal stacking, n of matrix1 must be equal to n of matrix2
matrix1 = np.array([[1,1,1]
                   ,[1,1,1]])
matrix2 = np.array([[0,0]
                   ,[0,0]])
print(np.hstack((matrix1, matrix2)))

[1 2 3 4 5 6 7 8 9 0]
------------------------------------------------
[[1 1 1 0 0]
 [1 1 1 0 0]]


In [49]:
# flatten
# convert any tensor to 1d array
array12 = np.arange(1, 21).reshape((5,4))
print(array12, "before flattening")
print(array12.flatten(), "after flattening")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] before flattening
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] after flattening


In [4]:
# Load and Save data
import os

In [11]:
data = np.genfromtxt('./sampledata.txt', delimiter=',')
print(data)
# change datatype to int
data = data.astype("int32")
print(data)
print(data.shape)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
(3, 18)
